export { show } from './startnow/startNowActions'
export {dashClose,dashOpen} from './dashmenu/dashmenuActions'
export {setTemplate,setStatus,setTextTransform,setTitleTransform,setObj,setDesc,setDescBg,setBorder,setDescColor,setDescSize,setFont,setTitle,setTitleBg,setTitleColor,setTitleSize} from './noteedit/NoteEditActions'
export {setMove,leftFalse,leftTrue,rightFalse,rightTrue} from './addNoteArrows/NoteArrowsActions'
export {fontOff,fontOn} from './fontMenu/fontMenuActions'
export {alertOff,alertOn} from './alertDelete/alertDeleteActions'
export {menuDesktopClose,menuDesktopOpen} from './menuDesktop/menuDesktopActions'
export {TouseFalse,TouseTrue} from './touse/ToUseActions'
export {loadingFalse,loadingTrue} from './showLoadingAdd/showLoadingAddActions'